---
- hosts: standalone
  become: true
  become_user: stack
  gather_facts: false
  vars_files: vars/defaults.yaml

  tasks:

  - name: Get minimum ansible facts
    setup:
      gather_subset: min


  # NOTE(mdbooth): The deploy step consistently fails to return. It fails in a
  # manner consistent with a hung SSH connection. The following dance is an
  # effort to never have a very long-running ansible task which might hang.
  - name: Set deploy log file location
    set_fact:
      tripleo_deploy_logs: "{{ ansible_env.HOME }}/tripleo-deploy.log"
      # Create this in /usr/local/bin because we execute it with systemd-run,
      # which requires an executable SELinux label
      tripleo_deploy_path: "/usr/local/bin/tripleo-deploy.sh"

  - name: Create the deploy script
    template:
      src: tripleo-deploy.sh.j2
      dest: "{{ tripleo_deploy_path }}"
      owner: root
      group: root
      mode: 0755
    vars:
      stack_home: "{{ ansible_env.HOME }}"
    become: true
    become_user: root

  - name: Truncate the log file
    copy:
      dest: "{{ tripleo_deploy_logs }}"
      content: ""

  # NOTE(mdbooth): Despite it using sudo, we want to run the deploy script as
  # the stack user so it gets the stack user's environment and creates things in
  # the stack user's home directory.

  - name: Cleanup in case of previous network failure.
    command: systemctl reset-failed
    become: true
    become_user: root
    tags:
      - deploy

  - name: Execute tripleo deploy
    command: systemd-run --unit=tripleo-deploy --uid=stack --gid=wheel -- {{ tripleo_deploy_path }}
    become: true
    become_user: root
    tags:
      - deploy

  - name: Wait for the deploy to complete
    command: systemctl show -p SubState --value tripleo-deploy
    register: tripleo_deploy_state
    until: tripleo_deploy_state is not failed and tripleo_deploy_state.stdout != "running"
    retries: 120 # 2 hours
    delay: 60
    tags:
      - deploy

  - name: Cleanup and exit on failure
    block:
    - name: Reset transient systemd unit
      command: systemctl reset-failed tripleo-deploy
      become: true
      become_user: root

    - fail:
        msg: TripleO deploy failed. See {{ tripleo_deploy_logs }} for details.
    when: tripleo_deploy_state.stdout == "failed"
    tags:
      - deploy
